- name: Setup dotfiles and configurations
  hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    # Common tasks for all systems (WSL & Linux)
    - include_tasks: tasks/common/install_packages.yml
    - include_tasks: tasks/common/configure_git.yml

    # Tasks for full Linux distributions (NOT WSL)
    - name: Add Repositories on Linux (Non-WSL)
      when: "'microsoft' not in ansible_facts['kernel'].lower()"
      include_tasks: tasks/linux/add_repos.yml

    - name: Add Flatpak on Linux (Non-WSL)
      when: "'microsoft' not in ansible_facts['kernel'].lower()"
      include_tasks: tasks/linux/add_flatpak_software.yml

    # Tasks for WSL-only
    # - name: Configure WSL-specific settings
    #   when: "'microsoft' in ansible_facts['kernel'].lower() or 'WSL_DISTRO_NAME' in ansible_env"
    #   include_tasks: tasks/wsl/setup_wsl_config.yml
