---
# tasks/main.yml - Main tasks for zsh role

- name: "ZSH | Set role variables"
  ansible.builtin.set_fact:
    zsh_config_dir: "{{ ansible_env.HOME }}/.zsh"
    zsh_config_file: "{{ ansible_env.HOME }}/.zshrc"
    zsh_user: "{{ ansible_env.USER | default(ansible_user_id) }}"

- name: "ZSH | Ensure ZSH is installed"
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: "ZSH | Ensure configuration directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ zsh_config_dir }}"
    - "{{ zsh_config_dir }}/functions"
    - "{{ zsh_config_dir }}/aliases"

- name: "ZSH | Check for distribution-specific tasks"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "ZSH | Run distribution-specific tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "ZSH | Copy git aliases"
  ansible.builtin.copy:
    src: "config/git_aliases.zsh"
    dest: "{{ zsh_config_dir }}/aliases/git_aliases.zsh"
    mode: '0644'

- name: "ZSH | Copy git functions"
  ansible.builtin.copy:
    src: "config/git_functions.zsh"
    dest: "{{ zsh_config_dir }}/functions/git_functions.zsh"
    mode: '0644'
