---
# tasks/main.yml - Main tasks for zsh role

- name: "ZSH | Set role variables"
  ansible.builtin.set_fact:
    zsh_config_dir: "{{ ansible_env.HOME }}/.zsh"
    zsh_config_file: "{{ ansible_env.HOME }}/.zshrc"
    zsh_user: "{{ ansible_env.USER | default(ansible_user_id) }}"

- name: "ZSH | Ensure ZSH is installed"
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: "ZSH | Ensure configuration directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ zsh_config_dir }}"
    - "{{ zsh_config_dir }}/functions"
    - "{{ zsh_config_dir }}/aliases"

- name: "ZSH | Check for distribution-specific tasks"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "ZSH | Run distribution-specific tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "ZSH | Copy alias files"
  ansible.builtin.copy:
    src: "config/{{ item }}"
    dest: "{{ zsh_config_dir }}/aliases/{{ item }}"
    mode: '0644'
  with_items:
    - "git_aliases.zsh"
    - "neovim_aliases.zsh"

- name: "ZSH | Copy function files"
  ansible.builtin.copy:
    src: "config/{{ item }}"
    dest: "{{ zsh_config_dir }}/functions/{{ item }}"
    mode: '0644'
  with_items:
    - "git_functions.zsh"
    - "neovim_functions.zsh"

- name: "ZSH | Copy OS-specific functions"
  ansible.builtin.copy:
    src: "commands/{{ ansible_distribution }}/os_functions.zsh"
    dest: "{{ zsh_config_dir }}/functions/os_functions.zsh"
    mode: '0644'
  when: ansible_distribution in ['Ubuntu', 'MacOSX']

- name: "ZSH | Copy ZSH config files"
  ansible.builtin.copy:
    src: "config/{{ item }}"
    dest: "{{ zsh_config_dir }}/{{ item }}"
    mode: '0644'
  with_items:
    - "fzf_config.zsh"
    - "history.zsh"
    - "vars.zsh"

- name: "ZSH | Install Starship prompt"
  ansible.builtin.include_tasks: "{{ role_path }}/utils/starship.yml"

- name: "ZSH | Copy .zshrc configuration file"
  ansible.builtin.copy:
    src: "config/.zshrc"
    dest: "{{ zsh_config_file }}"
    mode: '0644'