---
- name: "ZSH | Ubuntu | Update apt cache"
  ansible.builtin.apt:
    update_cache: yes
  become: true
  changed_when: false

- name: "ZSH | Ubuntu | Check if ZSH is already the default shell"
  ansible.builtin.command: "echo $SHELL"
  register: current_shell
  changed_when: false
  check_mode: false

- name: "ZSH | Ubuntu | Set ZSH as default shell"
  ansible.builtin.user:
    name: "{{ zsh_user }}"
    shell: /usr/bin/zsh
  become: true
  when: "'/zsh' not in current_shell.stdout