---
- name: "Warp | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: warp_distribution_config

- name: "Warp | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when:
    - warp_distribution_config.stat.exists
    - not ansible_host_environment_is_wsl
