# Template for later usage
# Example configuration
user:
  name: "Your Name"
  email: "your.email@example.com"

# Choose which components to install
components:
  neovim: true
  tmux: true
  vscode: false
  i3wm: false
  
# Language-specific tools
languages:
  javascript: true
  python: true
  go: false
  rust: false