user:
  name: "Your Name"
  email: "your.email@example.com"

default:
  fonts: true
  git: true
  zoxide: true
  zsh: true

terminal:
  neovim: true
  tmux: true
  i3wm: false

languages:
  javascript: true
  python: true
  go: true
  rust: true
  lua: true # required for nvim

utility:
  bat: true
  btop: true
  docker: true
  flatpak: true
  vscode: false
  tldr: true
  nvm: true
  npm: true
  nerdfetch: true # required for nvim
  neofetch: true # required for nvim
  lazygit: true
  gh: true
  fzf: true # required by nvim, zsh, tmux

flatpak_software:
  discord: false

