user:
  name: "Your Name"
  email: "your.email@example.com"
  username: "your_github_username"

# Choose which components to install
components:
  neovim: false
  tmux: false
  vscode: false
  i3wm: false
  
# Language-specific tools
languages:
  javascript: true
  python: true
  go: false
  rust: false