- name: "OHMYZSH | Check if Oh My Zsh is installed"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: omz_installed

- name: "OHMYZSH | Install Oh My Zsh"
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: not omz_installed.stat.exists
