---
- name: "ZSH | Check if Starship is already installed"
  ansible.builtin.command: "which starship"
  register: starship_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: "ZSH | Download Starship install script"
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  when: starship_check.rc != 0

- name: "ZSH | Install Starship"
  ansible.builtin.command: "/tmp/starship_install.sh -y"
  become: true
  when: starship_check.rc != 0

- name: "ZSH | Remove Starship install script"
  ansible.builtin.file:
    path: /tmp/starship_install.sh
    state: absent
  when: starship_check.rc != 0