---
- name: Install essential packages
  apt:
    name:
      - zsh
      - git
      - curl
      - build-essential
      - software-properties-common
      - python3-pip
      - yarn
      - htop
      - unzip
      - ripgrep
      - docker.io
      - docker-compose
      - openjdk-11-jdk
      - postgresql
      - sqlite3
      - python3-venv
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - python3-virtualenv
      - gcc
      - g++
      - make
      - cmake
      - clang
      - llvm
      - gdb
      - valgrind
      - strace
      - ltrace
      - lldb
      - jq
      - tree
      - wget
      - rsync
      - ssh
      - openssh-server
      - net-tools
      - dnsutils
      - iputils-ping
      - traceroute
      - whois
      - nmap
      - tcpdump
      - iperf3
      - iproute2
      - iptables
      - ufw
      - fail2ban
    state: present
    update_cache: yes