---
- name: Install Zsh
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Set Zsh as default shell
  user:
    name: "{{ default_user }}"
    shell: /usr/bin/zsh
