---
- name: Install essential packages
  apt:
    name:
      - zsh
      - git
      - curl
      - build-essential
      - software-properties-common
      - tmux
      - python3-pip
      - npm
      - yarn
      - nvm
      - code

    state: present
    update_cache: yes
