---
- name: "Goreleaser | Add Apt Repository"
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] https://repo.goreleaser.com/apt/ /"
    filename: "goreleaser"
    state: present
    update_cache: true
    mode: "0644"
  become: true

- name: "Goreleaser | Install Goreleaser"
  ansible.builtin.apt:
    name: goreleaser
    state: present
  become: true
