---
- name: "Warp | Add APT Key"
  ansible.builtin.apt_key:
    url: https://releases.warp.dev/linux/keys/warp.asc
    keyring: /etc/apt/keyrings/warpdotdev.gpg
    state: present
  become: true

- name: "Warp | Add APT Repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main"
    filename: warpdotdev
    state: present
    mode: "0644"
  become: true

- name: "Warp | Install Warp"
  ansible.builtin.apt:
    name: warp-terminal
    state: present
    update_cache: true
  become: true
