- name: Setup dotfiles and configurations
  hosts: localhost
  become: true
  connection: local

  pre_tasks:
    - name: Load external config file
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../rig_config.yml"
      tags:
        - always

    - name: Load role dependencies
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/role_dependencies.yml"
      tags:
        - always

    - name: Debug Loaded Variables
      ansible.builtin.debug:
        var: default
      tags:
        - always

    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Detect WSL Environment
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User (WSL)
      ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User (Linux/macOS)
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Compute enabled roles from config.yml
      ansible.builtin.set_fact:
        run_roles: >-
          {{ (default | default({}) | dict2items | selectattr('value', 'equalto', true) | map(attribute='key')) +
             (terminal | default({}) | dict2items | selectattr('value', 'equalto', true) | map(attribute='key')) +
             (languages | default({}) | dict2items | selectattr('value', 'equalto', true) | map(attribute='key')) +
             (utility | default({}) | dict2items | selectattr('value', 'equalto', true) | map(attribute='key')) +
             (flatpak_software | default({}) | dict2items | selectattr('value', 'equalto', true) | map(attribute='key')) }}
      tags:
        - always

    - name: Expand role dependencies
      ansible.builtin.set_fact:
        run_roles: "{{ run_roles + (dependencies | default({}) | dict2items | selectattr('key', 'in', run_roles) | map(attribute='value') | list | flatten) }}"

    - name: Remove explicitly disabled roles
      ansible.builtin.set_fact:
        run_roles: "{{ run_roles | difference((default + terminal + languages + utility + flatpak_software) | default({}) | dict2items | selectattr('value', 'equalto', false) | map(attribute='key') | list) }}"

    - name: Run roles based on config.yml
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags:
        - always
