- name: Setup dotfiles and configurations
  hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/common/install_packages.yml
    - include_tasks: tasks/common/configure_git.yml

    - name: Add Repositories on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu' and not ansible_facts['kernel'].startswith('Microsoft')
      include_tasks: tasks/ubuntu/add_repos.yml

    - name: Add Flatpak on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu' and not ansible_facts['kernel'].startswith('Microsoft')
      include_tasks: tasks/ubuntu/add_flatpak_software.yml

    # This will be only on WSL
    # - name: Only on WSL
    #   when: ansible_facts['distribution'] == 'Ubuntu' and 'microsoft' in ansible_facts['distribution_version'].lower()
    #   include_tasks: tasks/setup_wsl_config.yml
