---
- name: Setup dotfiles and configurations
  hosts: localhost
  become: yes
  vars_files:
    - ansible/vars/main.yml
  tasks:
    - include_tasks: ansible/tasks/install_packages.yml
    - include_tasks: ansible/tasks/install_zsh.yml
    - include_tasks: ansible/tasks/configure_git.yml
    - include_tasks: ansible/tasks/setup_vscode.yml
