---
- name: ZSH | Cleanup oh-my-zsh install script
  ansible.builtin.file:
    path: /{{ ansible_user_dir }}/oh-my-zsh.install.sh
    state: absent

- name: "ZSH | Check if Oh My Zsh is installed"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: "ZSH | Install Oh My Zsh"
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"
  when: not oh_my_zsh_installed.stat.exists

- name: "ZSH | Check if powerlevel10k is installed"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: p10k_installed

- name: "ZSH | Install powerlevel10k theme"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  when: not p10k_installed.stat.exists